# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-19 07:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='\u6807\u9898')),
                ('pic', models.URLField(verbose_name='\u5c01\u9762')),
            ],
        ),
    ]
